title: Lenasha Williams
description: Web & Security Engineer
site_title: 'lenasha williams'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://lolli1486.github.io
email: lenashawilliams554@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/

# Google Analytics ID
google_analytics: 